<?php

use Illuminate\Support\Facades\DB;

return function (array $ctx): void {
    $h = $ctx['h'];
    $gestionId = $h->id('gestion_academica', 'nombre', '2026-1');
    $adminId = $h->id('usuario', 'nombre_usuario', env('ADMIN_INITIAL_USERNAME', 'admin'));

    $applicants = [
        ['ci' => '1001001', 'nombres' => 'Luis', 'ap' => 'Molina', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '1001002', 'nombres' => 'Camila', 'ap' => 'Vargas', 'am' => 'Soto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-3'],
        ['ci' => '1001003', 'nombres' => 'Mateo', 'ap' => 'Rivera', 'am' => 'Duran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-4'],
        ['ci' => '1001004', 'nombres' => 'Valeria', 'ap' => 'Ortiz', 'am' => 'Cespedes', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '1001005', 'nombres' => 'Diego', 'ap' => 'Salazar', 'am' => 'Paz', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-5'],
        ['ci' => '1001006', 'nombres' => 'Sofia', 'ap' => 'Ledezma', 'am' => 'Vaca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-6'],
        ['ci' => '1001007', 'nombres' => 'Gabriel', 'ap' => 'Flores', 'am' => 'Nunez', 'estado_req' => 'aprobado', 'estado_pago' => 'pendiente', 'estado' => 'pendiente_pago', 'doc' => 'aprobado', 'pago' => 'pendiente', 'p1' => '187-5', 'p2' => '187-3'],
        ['ci' => '1001008', 'nombres' => 'Luciana', 'ap' => 'Mercado', 'am' => 'Villarroel', 'estado_req' => 'pendiente', 'estado_pago' => 'pendiente', 'estado' => 'registrado', 'doc' => 'pendiente', 'pago' => null, 'p1' => '187-6', 'p2' => '187-4'],
        ['ci' => '1001009', 'nombres' => 'Pablo', 'ap' => 'Cuellar', 'am' => 'Aguirre', 'estado_req' => 'rechazado', 'estado_pago' => 'rechazado', 'estado' => 'rechazado', 'doc' => 'rechazado', 'pago' => 'rechazado', 'p1' => '187-3', 'p2' => '187-6'],
        ['ci' => '1001010', 'nombres' => 'Daniela', 'ap' => 'Justiniano', 'am' => 'Mendez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000001', 'nombres' => 'Adrian', 'ap' => 'Aguilar', 'am' => 'Arias', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000002', 'nombres' => 'Alejandra', 'ap' => 'Arce', 'am' => 'Daza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000003', 'nombres' => 'Andres', 'ap' => 'Barrera', 'am' => 'Montero', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000004', 'nombres' => 'Andrea', 'ap' => 'Cabrera', 'am' => 'Terceros', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000005', 'nombres' => 'Bruno', 'ap' => 'Camacho', 'am' => 'Zurita', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000006', 'nombres' => 'Carla', 'ap' => 'Castillo', 'am' => 'Calderon', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000007', 'nombres' => 'Carlos', 'ap' => 'Chavez', 'am' => 'Lima', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000008', 'nombres' => 'Cecilia', 'ap' => 'Contreras', 'am' => 'Sanchez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000009', 'nombres' => 'Cristian', 'ap' => 'Espinoza', 'am' => 'Yanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000010', 'nombres' => 'Diana', 'ap' => 'Fernandez', 'am' => 'Beltran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000011', 'nombres' => 'Eduardo', 'ap' => 'Garcia', 'am' => 'Gomez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000012', 'nombres' => 'Elena', 'ap' => 'Gutierrez', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000013', 'nombres' => 'Fernando', 'ap' => 'Herrera', 'am' => 'Villalba', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000014', 'nombres' => 'Gabriela', 'ap' => 'Lopez', 'am' => 'Baldivieso', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000015', 'nombres' => 'Gonzalo', 'ap' => 'Mamani', 'am' => 'Flores', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000016', 'nombres' => 'Isabel', 'ap' => 'Medina', 'am' => 'Orellana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000017', 'nombres' => 'Javier', 'ap' => 'Morales', 'am' => 'Valdez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000018', 'nombres' => 'Jimena', 'ap' => 'Navarro', 'am' => 'Arteaga', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000019', 'nombres' => 'Kevin', 'ap' => 'Paredes', 'am' => 'Cardenas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000020', 'nombres' => 'Laura', 'ap' => 'Pereira', 'am' => 'Mendoza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000021', 'nombres' => 'Marcelo', 'ap' => 'Quiroga', 'am' => 'Soria', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000022', 'nombres' => 'Mariana', 'ap' => 'Ramirez', 'am' => 'Zambrana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000023', 'nombres' => 'Nicolas', 'ap' => 'Rojas', 'am' => 'Caceres', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000024', 'nombres' => 'Natalia', 'ap' => 'Saavedra', 'am' => 'Ibanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000025', 'nombres' => 'Oscar', 'ap' => 'Suarez', 'am' => 'Salinas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000026', 'nombres' => 'Paola', 'ap' => 'Torrez', 'am' => 'Villarroel', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000027', 'nombres' => 'Rafael', 'ap' => 'Urquidi', 'am' => 'Barrios', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000028', 'nombres' => 'Renata', 'ap' => 'Vargas', 'am' => 'Galarza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000029', 'nombres' => 'Sebastian', 'ap' => 'Velasco', 'am' => 'Pinto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000030', 'nombres' => 'Tatiana', 'ap' => 'Zeballos', 'am' => 'Vega', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000031', 'nombres' => 'Adrian', 'ap' => 'Aguilar', 'am' => 'Arias', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000032', 'nombres' => 'Alejandra', 'ap' => 'Arce', 'am' => 'Daza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000033', 'nombres' => 'Andres', 'ap' => 'Barrera', 'am' => 'Montero', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000034', 'nombres' => 'Andrea', 'ap' => 'Cabrera', 'am' => 'Terceros', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000035', 'nombres' => 'Bruno', 'ap' => 'Camacho', 'am' => 'Zurita', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000036', 'nombres' => 'Carla', 'ap' => 'Castillo', 'am' => 'Calderon', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000037', 'nombres' => 'Carlos', 'ap' => 'Chavez', 'am' => 'Lima', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000038', 'nombres' => 'Cecilia', 'ap' => 'Contreras', 'am' => 'Sanchez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000039', 'nombres' => 'Cristian', 'ap' => 'Espinoza', 'am' => 'Yanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000040', 'nombres' => 'Diana', 'ap' => 'Fernandez', 'am' => 'Beltran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000041', 'nombres' => 'Eduardo', 'ap' => 'Garcia', 'am' => 'Gomez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000042', 'nombres' => 'Elena', 'ap' => 'Gutierrez', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000043', 'nombres' => 'Fernando', 'ap' => 'Herrera', 'am' => 'Villalba', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000044', 'nombres' => 'Gabriela', 'ap' => 'Lopez', 'am' => 'Baldivieso', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000045', 'nombres' => 'Gonzalo', 'ap' => 'Mamani', 'am' => 'Flores', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000046', 'nombres' => 'Isabel', 'ap' => 'Medina', 'am' => 'Orellana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000047', 'nombres' => 'Javier', 'ap' => 'Morales', 'am' => 'Valdez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000048', 'nombres' => 'Jimena', 'ap' => 'Navarro', 'am' => 'Arteaga', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000049', 'nombres' => 'Kevin', 'ap' => 'Paredes', 'am' => 'Cardenas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000050', 'nombres' => 'Laura', 'ap' => 'Pereira', 'am' => 'Mendoza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000051', 'nombres' => 'Marcelo', 'ap' => 'Quiroga', 'am' => 'Soria', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000052', 'nombres' => 'Mariana', 'ap' => 'Ramirez', 'am' => 'Zambrana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000053', 'nombres' => 'Nicolas', 'ap' => 'Rojas', 'am' => 'Caceres', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000054', 'nombres' => 'Natalia', 'ap' => 'Saavedra', 'am' => 'Ibanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000055', 'nombres' => 'Oscar', 'ap' => 'Suarez', 'am' => 'Salinas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000056', 'nombres' => 'Paola', 'ap' => 'Torrez', 'am' => 'Villarroel', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000057', 'nombres' => 'Rafael', 'ap' => 'Urquidi', 'am' => 'Barrios', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000058', 'nombres' => 'Renata', 'ap' => 'Vargas', 'am' => 'Galarza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000059', 'nombres' => 'Sebastian', 'ap' => 'Velasco', 'am' => 'Pinto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000060', 'nombres' => 'Tatiana', 'ap' => 'Zeballos', 'am' => 'Vega', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000061', 'nombres' => 'Adrian', 'ap' => 'Aguilar', 'am' => 'Arias', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000062', 'nombres' => 'Alejandra', 'ap' => 'Arce', 'am' => 'Daza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000063', 'nombres' => 'Andres', 'ap' => 'Barrera', 'am' => 'Montero', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000064', 'nombres' => 'Andrea', 'ap' => 'Cabrera', 'am' => 'Terceros', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000065', 'nombres' => 'Bruno', 'ap' => 'Camacho', 'am' => 'Zurita', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000066', 'nombres' => 'Carla', 'ap' => 'Castillo', 'am' => 'Calderon', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000067', 'nombres' => 'Carlos', 'ap' => 'Chavez', 'am' => 'Lima', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000068', 'nombres' => 'Cecilia', 'ap' => 'Contreras', 'am' => 'Sanchez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000069', 'nombres' => 'Cristian', 'ap' => 'Espinoza', 'am' => 'Yanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000070', 'nombres' => 'Diana', 'ap' => 'Fernandez', 'am' => 'Beltran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000071', 'nombres' => 'Eduardo', 'ap' => 'Garcia', 'am' => 'Gomez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000072', 'nombres' => 'Elena', 'ap' => 'Gutierrez', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000073', 'nombres' => 'Fernando', 'ap' => 'Herrera', 'am' => 'Villalba', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000074', 'nombres' => 'Gabriela', 'ap' => 'Lopez', 'am' => 'Baldivieso', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000075', 'nombres' => 'Gonzalo', 'ap' => 'Mamani', 'am' => 'Flores', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000076', 'nombres' => 'Isabel', 'ap' => 'Medina', 'am' => 'Orellana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000077', 'nombres' => 'Javier', 'ap' => 'Morales', 'am' => 'Valdez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000078', 'nombres' => 'Jimena', 'ap' => 'Navarro', 'am' => 'Arteaga', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000079', 'nombres' => 'Kevin', 'ap' => 'Paredes', 'am' => 'Cardenas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000080', 'nombres' => 'Laura', 'ap' => 'Pereira', 'am' => 'Mendoza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000081', 'nombres' => 'Marcelo', 'ap' => 'Quiroga', 'am' => 'Soria', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000082', 'nombres' => 'Mariana', 'ap' => 'Ramirez', 'am' => 'Zambrana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000083', 'nombres' => 'Nicolas', 'ap' => 'Rojas', 'am' => 'Caceres', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000084', 'nombres' => 'Natalia', 'ap' => 'Saavedra', 'am' => 'Ibanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000085', 'nombres' => 'Oscar', 'ap' => 'Suarez', 'am' => 'Salinas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000086', 'nombres' => 'Paola', 'ap' => 'Torrez', 'am' => 'Villarroel', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000087', 'nombres' => 'Rafael', 'ap' => 'Urquidi', 'am' => 'Barrios', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000088', 'nombres' => 'Renata', 'ap' => 'Vargas', 'am' => 'Galarza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000089', 'nombres' => 'Sebastian', 'ap' => 'Velasco', 'am' => 'Pinto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000090', 'nombres' => 'Tatiana', 'ap' => 'Zeballos', 'am' => 'Vega', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000091', 'nombres' => 'Adrian', 'ap' => 'Aguilar', 'am' => 'Arias', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000092', 'nombres' => 'Alejandra', 'ap' => 'Arce', 'am' => 'Daza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000093', 'nombres' => 'Andres', 'ap' => 'Barrera', 'am' => 'Montero', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000094', 'nombres' => 'Andrea', 'ap' => 'Cabrera', 'am' => 'Terceros', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000095', 'nombres' => 'Bruno', 'ap' => 'Camacho', 'am' => 'Zurita', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000096', 'nombres' => 'Carla', 'ap' => 'Castillo', 'am' => 'Calderon', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000097', 'nombres' => 'Carlos', 'ap' => 'Chavez', 'am' => 'Lima', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000098', 'nombres' => 'Cecilia', 'ap' => 'Contreras', 'am' => 'Sanchez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000099', 'nombres' => 'Cristian', 'ap' => 'Espinoza', 'am' => 'Yanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000100', 'nombres' => 'Diana', 'ap' => 'Fernandez', 'am' => 'Beltran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000101', 'nombres' => 'Eduardo', 'ap' => 'Garcia', 'am' => 'Gomez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000102', 'nombres' => 'Elena', 'ap' => 'Gutierrez', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000103', 'nombres' => 'Fernando', 'ap' => 'Herrera', 'am' => 'Villalba', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000104', 'nombres' => 'Gabriela', 'ap' => 'Lopez', 'am' => 'Baldivieso', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000105', 'nombres' => 'Gonzalo', 'ap' => 'Mamani', 'am' => 'Flores', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000106', 'nombres' => 'Isabel', 'ap' => 'Medina', 'am' => 'Orellana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000107', 'nombres' => 'Javier', 'ap' => 'Morales', 'am' => 'Valdez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000108', 'nombres' => 'Jimena', 'ap' => 'Navarro', 'am' => 'Arteaga', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000109', 'nombres' => 'Kevin', 'ap' => 'Paredes', 'am' => 'Cardenas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000110', 'nombres' => 'Laura', 'ap' => 'Pereira', 'am' => 'Mendoza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000111', 'nombres' => 'Marcelo', 'ap' => 'Quiroga', 'am' => 'Soria', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000112', 'nombres' => 'Mariana', 'ap' => 'Ramirez', 'am' => 'Zambrana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000113', 'nombres' => 'Nicolas', 'ap' => 'Rojas', 'am' => 'Caceres', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000114', 'nombres' => 'Natalia', 'ap' => 'Saavedra', 'am' => 'Ibanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000115', 'nombres' => 'Oscar', 'ap' => 'Suarez', 'am' => 'Salinas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000116', 'nombres' => 'Paola', 'ap' => 'Torrez', 'am' => 'Villarroel', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000117', 'nombres' => 'Rafael', 'ap' => 'Urquidi', 'am' => 'Barrios', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000118', 'nombres' => 'Renata', 'ap' => 'Vargas', 'am' => 'Galarza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000119', 'nombres' => 'Sebastian', 'ap' => 'Velasco', 'am' => 'Pinto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000120', 'nombres' => 'Tatiana', 'ap' => 'Zeballos', 'am' => 'Vega', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000121', 'nombres' => 'Adrian', 'ap' => 'Aguilar', 'am' => 'Arias', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000122', 'nombres' => 'Alejandra', 'ap' => 'Arce', 'am' => 'Daza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000123', 'nombres' => 'Andres', 'ap' => 'Barrera', 'am' => 'Montero', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000124', 'nombres' => 'Andrea', 'ap' => 'Cabrera', 'am' => 'Terceros', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000125', 'nombres' => 'Bruno', 'ap' => 'Camacho', 'am' => 'Zurita', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000126', 'nombres' => 'Carla', 'ap' => 'Castillo', 'am' => 'Calderon', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000127', 'nombres' => 'Carlos', 'ap' => 'Chavez', 'am' => 'Lima', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000128', 'nombres' => 'Cecilia', 'ap' => 'Contreras', 'am' => 'Sanchez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000129', 'nombres' => 'Cristian', 'ap' => 'Espinoza', 'am' => 'Yanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000130', 'nombres' => 'Diana', 'ap' => 'Fernandez', 'am' => 'Beltran', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000131', 'nombres' => 'Eduardo', 'ap' => 'Garcia', 'am' => 'Gomez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000132', 'nombres' => 'Elena', 'ap' => 'Gutierrez', 'am' => 'Roca', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000133', 'nombres' => 'Fernando', 'ap' => 'Herrera', 'am' => 'Villalba', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000134', 'nombres' => 'Gabriela', 'ap' => 'Lopez', 'am' => 'Baldivieso', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000135', 'nombres' => 'Gonzalo', 'ap' => 'Mamani', 'am' => 'Flores', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000136', 'nombres' => 'Isabel', 'ap' => 'Medina', 'am' => 'Orellana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000137', 'nombres' => 'Javier', 'ap' => 'Morales', 'am' => 'Valdez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000138', 'nombres' => 'Jimena', 'ap' => 'Navarro', 'am' => 'Arteaga', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000139', 'nombres' => 'Kevin', 'ap' => 'Paredes', 'am' => 'Cardenas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000140', 'nombres' => 'Laura', 'ap' => 'Pereira', 'am' => 'Mendoza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000141', 'nombres' => 'Marcelo', 'ap' => 'Quiroga', 'am' => 'Soria', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000142', 'nombres' => 'Mariana', 'ap' => 'Ramirez', 'am' => 'Zambrana', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000143', 'nombres' => 'Nicolas', 'ap' => 'Rojas', 'am' => 'Caceres', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000144', 'nombres' => 'Natalia', 'ap' => 'Saavedra', 'am' => 'Ibanez', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000145', 'nombres' => 'Oscar', 'ap' => 'Suarez', 'am' => 'Salinas', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000146', 'nombres' => 'Paola', 'ap' => 'Torrez', 'am' => 'Villarroel', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
        ['ci' => '2000147', 'nombres' => 'Rafael', 'ap' => 'Urquidi', 'am' => 'Barrios', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-5', 'p2' => '187-6'],
        ['ci' => '2000148', 'nombres' => 'Renata', 'ap' => 'Vargas', 'am' => 'Galarza', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-6', 'p2' => '187-3'],
        ['ci' => '2000149', 'nombres' => 'Sebastian', 'ap' => 'Velasco', 'am' => 'Pinto', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-3', 'p2' => '187-4'],
        ['ci' => '2000150', 'nombres' => 'Tatiana', 'ap' => 'Zeballos', 'am' => 'Vega', 'estado_req' => 'aprobado', 'estado_pago' => 'pagado', 'estado' => 'pagado', 'doc' => 'aprobado', 'pago' => 'pagado', 'p1' => '187-4', 'p2' => '187-5'],
    ];

    foreach ($applicants as $index => $applicant) {
        $personaId = $h->person([
            'cedula_identidad' => $applicant['ci'],
            'nombres' => $applicant['nombres'],
            'apellido_paterno' => $applicant['ap'],
            'apellido_materno' => $applicant['am'],
            'fecha_nacimiento' => '2007-'.str_pad((string) (($index % 9) + 1), 2, '0', STR_PAD_LEFT).'-12',
            'sexo' => $index % 2 === 0 ? 'Masculino' : 'Femenino',
            'direccion' => 'Zona demo postulante '.$applicant['ci'],
            'telefono' => null,
            'celular' => '72000'.str_pad((string) ($index + 1), 3, '0', STR_PAD_LEFT),
            'correo' => strtolower($applicant['nombres']).'.'.$applicant['ci'].'@postulante.cupficct.local',
            'ciudad' => 'Santa Cruz',
        ]);

        DB::table('postulante')->updateOrInsert(
            ['persona_id' => $personaId],
            [
                'gestion_academica_id' => $gestionId,
                'colegio_procedencia' => 'Colegio Demo FICCT '.(($index % 4) + 1),
                'estado_requisitos' => $applicant['estado_req'],
                'estado_pago' => $applicant['estado_pago'],
                'estado_postulante' => $applicant['estado'],
                'observacion' => $applicant['estado'] === 'rechazado' ? 'Registro demo rechazado por requisito observado.' : null,
                'creado_en' => $h->now(),
                'actualizado_en' => $h->now(),
            ]
        );

        $postulanteId = (int) DB::table('postulante')->where('persona_id', $personaId)->value('id');

        DB::table('postulacion')->updateOrInsert(
            ['postulante_id' => $postulanteId],
            [
                'primera_carrera_id' => $h->id('carrera', 'codigo', $applicant['p1']),
                'segunda_carrera_id' => $h->id('carrera', 'codigo', $applicant['p2']),
                'carrera_asignada_id' => null,
                'motivo_asignacion' => null,
                'promedio_final' => null,
                'estado_final' => null,
                'orden_prioridad' => null,
                'asignado_en' => null,
            ]
        );

        DB::table('documento_postulante')->updateOrInsert(
            ['postulante_id' => $postulanteId, 'tipo_documento' => 'titulo_bachiller'],
            [
                'cloudinary_public_id' => 'demo/titulo_bachiller/'.$applicant['ci'],
                'cloudinary_url' => '/poblar_db/img/titulo_bachiller_generico.jpg',
                'formato_archivo' => 'jpg',
                'subido_en' => $h->now(),
                'estado_revision' => $applicant['doc'],
                'observacion' => $applicant['doc'] === 'rechazado' ? 'Documento ilegible en datos demo.' : null,
            ]
        );

        if ($applicant['pago'] !== null) {
            DB::table('pago_stripe')->updateOrInsert(
                ['postulante_id' => $postulanteId],
                [
                    'stripe_payment_intent_id' => 'pi_demo_'.$applicant['ci'],
                    'stripe_checkout_session_id' => 'cs_demo_'.$applicant['ci'],
                    'monto' => 250.00,
                    'moneda' => 'BOB',
                    'estado_pago' => $applicant['pago'],
                    'fecha_pago' => $applicant['pago'] === 'pagado' ? $h->now() : null,
                    'respuesta_stripe' => $h->json(['demo' => true, 'ci' => $applicant['ci']]),
                    'validado_por_usuario_id' => $applicant['pago'] === 'pagado' ? $adminId : null,
                    'validado_en' => $applicant['pago'] === 'pagado' ? $h->now() : null,
                    'creado_en' => $h->now(),
                ]
            );
        }
    }
};
